### ISSUE TITLE
WarLogs

### ISSUE THREAD

**Issue by shivampaw** [1n9i9c7om/ClashOfClans-API-PHP#11]
Hi,

Can someone add a class for warlogs??

**Comment by 1n9i9c7om** [comment]
Sorry for that late response!
I'll start working on it this week, promise!

**Comment by shivampaw** [comment]
I've been working on this. I'll submit a pull request later this week as I am on holiday.

**Comment by 1n9i9c7om** [comment]
Ah, I've just done it and pushed a pull request. Go ahead and submit yours anyways, maybe it's better. :P
