### ISSUE TITLE
Non-Object

### ISSUE THREAD

**Issue by RepeaterCreeper** [1n9i9c7om/ClashOfClans-API-PHP#13]
Everything I do is being met with `Notice: Trying to get property of non-object in C:\xampp\htdocs\Clan Link\requests\ClashAPI\Clan.class.php on line 115`

![image](https://cloud.githubusercontent.com/assets/2164489/17452646/64841b30-5b2e-11e6-8fec-272963f83617.png)

Checked:
- [x] API Key - I've used this with another API just to make sure it works and YES it does.
- [x] cURL in xampp - Checked and yes it does exist as my previous API actually uses cURL.

As previously stated the CODE is the exact replica of the "Examples: clanInformation.php" even the location of the API.class.php is the same.

**Comment by 1n9i9c7om** [comment]
In _API.class.php_, add a var_dump to sendRequest (line 24), like this:

``` php
    protected function sendRequest($url)
    {
        $ch = curl_init(); 
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'authorization: Bearer '.$this->_apiKey // 
        ));
        $output = curl_exec($ch);
        curl_close($ch); 
        var_dump($output); //this is the new addition
        return $output;
    }
```

This should allow better debugging. What is it showing now?

**Comment by RepeaterCreeper** [comment]
![image](https://cloud.githubusercontent.com/assets/2164489/17463904/340def5a-5c8f-11e6-9c2d-76d329951312.png)

`bool(false) bool(false)`

**Comment by RepeaterCreeper** [comment]
Never mind I figured it out. I remembered that the API Wrapper I used didn't work either until my friend suggested I add this `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`. Finally it works. :)
