### ISSUE TITLE
Library as package

### ISSUE THREAD

**Issue by arcanewater** [1n9i9c7om/ClashOfClans-API-PHP#4]
Thanks for previous update, one more question possible to port this lib to composer? So it will be easyer to use it with Laravel ?

**Comment by 1n9i9c7om** [comment]
Sorry, but I have no plans to create a Composer package anytime soon, as I'm not experienced with it at all.  
However, as this project is open source (and underlying a license that allows you to do literally everything), everybody is allowed to create one.
