### ISSUE TITLE
Slow loading league badges

### ISSUE THREAD

**Issue by RHITNL** [1n9i9c7om/ClashOfClans-API-PHP#5]
Hi,

Thanks for this wrapper, really useful. Only have one issue.
As soon as I include the league badges for player by setting values for League.class.php, the load time of the whole clanmembers list is extremely slow.
When I disable the images, it fast as lightning.
Using the most recent version of all files so it should already have the caching changes in it.
Any idea what could cause this?

Regards,

Ralph

**Comment by 1n9i9c7om** [comment]
Hello, 

I think I know what's causing the issue. It's actually the same as to why [loading the rank toplist was slow in #3](https://github.com/1n9i9c7om/ClashOfClans-API-PHP/issues/3) - I fixed it for clans, but forgot about Leagues (and Locations). 

I'm currently heading back from school, expect an update later today or tomorrow - most likely today, tho. :) 

I'll comment back on this issue after its fixed.

**Comment by 1n9i9c7om** [comment]
It's fixed, you have to change a small thing about your code, though.  
Right now, you're passing the league ID to the constructor of the *_League.class_ - now, you can also pass the league itself, preventing an additional request per member (which is what causes the slow page loading).

Right now, you're probably doing something like this:

``` php
$clan = new CoC_Clan("#22UCCU0J");

foreach ($clan->getAllMembers() as $member) 
{
    $member = new CoC_Member($member);
    $league = new CoC_League($member->getLeagueId());

   echo "<img src=\"" . $league->getLeagueIcon("small") . "\">";
}
```

Now, with [the latest commit](https://github.com/1n9i9c7om/ClashOfClans-API-PHP/commit/3651e5e40ebe60e265d18c6c412cb7c3e832b094) I pushed, you can do it like this:

``` php
$clan = new CoC_Clan("#22UCCU0J");

foreach ($clan->getAllMembers() as $member) 
{
    $member = new CoC_Member($member);
    $league = new CoC_League($member->getLeague()); //call getLeague(), not getLeagueId()

   echo "<img src=\"" . $league->getLeagueIcon("small") . "\">";
}
```

[Example to test loading times](http://1n9i9c7om.com/coc/testLeagues.php) `Script Execution took 0.71272897720337 for 31 member.`
[Same code except that I'm using getLeagueId()](http://1n9i9c7om.com/coc/testLeagues.php?slow) `Script Execution took 7.0390779972076 for 31 member.`  
Sorry for forgetting about Leagues and Locations while fixing it for clans. :stuck_out_tongue:  
I hope it works for you now!

**Comment by RHITNL** [comment]
Brilliant! Was looking into that part but couldn't wrap my finger around it. It will save supercell a lot of server requests now 😀
Works fast and clean now!
[http://dutchbros.tk](url) if you are interested to see my use of your wrapper! (Work in progress)
